plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.16'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'

	implementation 'cn.zhxu:bean-searcher-boot-starter:4.8.12'
	implementation 'cn.zhxu:bean-searcher-label:4.8.12'
    implementation 'cn.zhxu:bean-searcher-exporter:4.8.12'

	runtimeOnly 'com.h2database:h2'

	compileOnly("org.projectlombok:lombok")
	annotationProcessor("org.projectlombok:lombok")

}
