plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	implementation 'cn.zhxu:bean-searcher-boot-starter:4.8.10'
	implementation 'cn.zhxu:bean-searcher-label:4.8.10'
	implementation 'cn.zhxu:bean-searcher-exporter:4.8.10'

	runtimeOnly 'com.h2database:h2'

	compileOnly("org.projectlombok:lombok")
	annotationProcessor("org.projectlombok:lombok")

}
