/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADatePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    FilterCard: typeof import('./src/components/FilterCard.vue')['default']
    HeroBanner: typeof import('./src/components/HeroBanner.vue')['default']
    RepoBanner: typeof import('./src/components/RepoBanner.vue')['default']
    ShowcaseBanner: typeof import('./src/components/ShowcaseBanner.vue')['default']
    SourceBanner: typeof import('./src/components/SourceBanner.vue')['default']
    StatsCards: typeof import('./src/components/StatsCards.vue')['default']
  }
}
