
db:
  jdbcUrl: jdbc:h2:~/bs-demo-solon
  driverClassName: org.h2.Driver
  username: sa
  password: 123456

# 为兼容前端 Element UI 的分页组件，它是从 1 开始的
bean-searcher:
  params:
    pagination:
      start: 1
  exporter:
    batch-delay: PT0.5S
